### ISSUE TITLE
firebase.js not included correctly

### ISSUE THREAD

**Issue by anissen** [jefvel/haxe-firebase#2]
Thanks for making this library -- it seems really useful! 👍 

The macro for including the firebase library does not seem to work correctly. I'm getting the following error
```
.../haxe-firebase/Sources/firebase/Firebase.hx:6: characters 35-52 : File not found 'lib/firebase.js'
```
Changing the `includeFile` from "lib/firebase.js" to "../lib/firebase.js" makes the compiler happy, but then I get the following error when trying to use library:

```
Firebase.hx:6 Uncaught TypeError: Cannot read property 'navigator' of undefined(…)
    (anonymous function) @ Firebase.hx:6
   console.undefined.log @ Firebase.hx:6
    (anonymous function) @ Firebase.hx:6
```

I have gotten this library to work by simply commenting out the inclusion of "firebase.js" and including `<script src="https://www.gstatic.com/firebasejs/3.6.1/firebase.js"></script>` directly in the HTML. However, it would be nice to get the library file packaged in this library.

**Comment by jefvel** [comment]
Yeah, adding a relative path seems better. But I'm not sure what causes that error you're getting afterwards. Can you run it in chrome to see a more detailed stack trace?

**Comment by anissen** [comment]
Here's the error output with the debug flag enabled:

```
Uncaught TypeError: Cannot read property 'navigator' of undefined
    at file:///(...)/haxe-firebase/test/Main.js:129:1539
    at console.undefined.log (file:///(...)/haxe-firebase/test/Main.js:148:101)
    at file:///(...)/haxe-firebase/test/Main.js:726:3
```

It might be related to how the file is included according to [this discussion](http://stackoverflow.com/questions/31221357/webpack-firebase-disable-parsing-of-firebase) among others.

Are you not experiencing this issue? How is your setup for building and running things that use this library?

**Comment by anissen** [comment]
I just found out that if I `"use strict";` from the top of the generated JavaScript file then it works! I wonder if there's a way to avoid having Haxe prepend this...

**Comment by jefvel** [comment]
It works if you remove "use strict";? For me it works both ways, with and without it. I could try building it with snow later, I'm currently testing using Kha.

**Comment by anissen** [comment]
For me it works _only_ without "use strict;" (which is the case when building with `-D js-classic`). I'm using Haxe 3.2.1 on Mac 10.11 and using the latest Chrome. I'm running a very simple test file embedded in an equally simple HTML-file (and no through a server).

**Comment by jefvel** [comment]
I'm using Haxe 3.3.0, maybe that could be the cause of the issue?

**Comment by anissen** [comment]
That's very likely. I'll close this issue, but you might want to stick a disclaimer on the readme saying that Haxe 3.2.1 needs to compile with `-D js-classic`. Thanks for you help! 👍

**Comment by jefvel** [comment]
I'll add that info, thanks!
